#!/bin/bash
set -euo pipefail

# CI wrapper only. Runtime behavior is owned by /start_redmine.sh.
export MIGRATIONS_ONLY_STARTUP="${MIGRATIONS_ONLY_STARTUP:-1}"
export RUN_DB_MIGRATE="${RUN_DB_MIGRATE:-1}"
export RUN_PLUGIN_MIGRATE="${RUN_PLUGIN_MIGRATE:-auto}"
export START_SERVER="${START_SERVER:-0}"
export START_CRON="${START_CRON:-0}"
export START_SOLID_QUEUE="${START_SOLID_QUEUE:-0}"
export ASSETS_PRECOMPILE="${ASSETS_PRECOMPILE:-1}"
export ASSETS_PRECOMPILE_FORCE="${ASSETS_PRECOMPILE_FORCE:-1}"
export STARTUP_ASSET_FIXES="${STARTUP_ASSET_FIXES:-1}"
export APPLY_A1_THEME_OVERRIDES_ON_BOOT="${APPLY_A1_THEME_OVERRIDES_ON_BOOT:-0}"
export RAILS_ENV="${RAILS_ENV:-test}"

exec /start_redmine.sh
