default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      concurrency_maintenance_interval: 300
  workers:
    - queues: "*"
      threads: <%= Integer(ENV.fetch("SOLID_QUEUE_THREADS", ENV.fetch("RAILS_MAX_THREADS", "5"))) %>
      polling_interval: 0.1

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
