-- SQL Query Comparison: Slow vs Fast
-- Environment: 02pre/taskman, Project: nanyt (ID: 161)
-- Date: 2026-04-29

-- ============================================
-- SLOW QUERY (Original)
-- Generated by: HelpdeskTicket.includes(:issue => [:project]).where(:projects => {:id => 161}).count
-- Performance: >120 seconds (TIMEOUT)
-- ============================================

SELECT `helpdesk_tickets`.`id` AS t0_r0, 
       `helpdesk_tickets`.`contact_id` AS t0_r1, 
       `helpdesk_tickets`.`issue_id` AS t0_r2, 
       `helpdesk_tickets`.`source` AS t0_r3, 
       `helpdesk_tickets`.`from_address` AS t0_r4, 
       `helpdesk_tickets`.`to_address` AS t0_r5, 
       `helpdesk_tickets`.`ticket_date` AS t0_r6, 
       `helpdesk_tickets`.`cc_address` AS t0_r7, 
       `helpdesk_tickets`.`message_id` AS t0_r8, 
       `helpdesk_tickets`.`is_incoming` AS t0_r9, 
       `helpdesk_tickets`.`reaction_time` AS t0_r10, 
       `helpdesk_tickets`.`first_response_time` AS t0_r11, 
       `helpdesk_tickets`.`resolve_time` AS t0_r12, 
       `helpdesk_tickets`.`last_agent_response_at` AS t0_r13, 
       `helpdesk_tickets`.`last_customer_response_at` AS t0_r14, 
       `helpdesk_tickets`.`vote` AS t0_r15, 
       `helpdesk_tickets`.`vote_comment` AS t0_r16, 
       `helpdesk_tickets`.`view_id` AS t0_r17, 
       `helpdesk_tickets`.`viewed_on` AS t0_r18, 
       `issues`.`id` AS t1_r0, 
       `issues`.`tracker_id` AS t1_r1, 
       `issues`.`project_id` AS t1_r2, 
       `issues`.`subject` AS t1_r3, 
       `issues`.`description` AS t1_r4, 
       `issues`.`due_date` AS t1_r5, 
       `issues`.`category_id` AS t1_r6, 
       `issues`.`status_id` AS t1_r7, 
       `issues`.`assigned_to_id` AS t1_r8, 
       `issues`.`priority_id` AS t1_r9, 
       `issues`.`fixed_version_id` AS t1_r10, 
       `issues`.`author_id` AS t1_r11, 
       `issues`.`lock_version` AS t1_r12, 
       `issues`.`created_on` AS t1_r13, 
       `issues`.`updated_on` AS t1_r14, 
       `issues`.`start_date` AS t1_r15, 
       `issues`.`done_ratio` AS t1_r16, 
       `issues`.`estimated_hours` AS t1_r17, 
       `issues`.`parent_id` AS t1_r18, 
       `issues`.`root_id` AS t1_r19, 
       `issues`.`lft` AS t1_r20, 
       `issues`.`rgt` AS t1_r21, 
       `issues`.`is_private` AS t1_r22, 
       `issues`.`closed_on` AS t1_r23, 
       `projects`.`id` AS t2_r0, 
       `projects`.`name` AS t2_r1, 
       `projects`.`description` AS t2_r2, 
       `projects`.`homepage` AS t2_r3, 
       `projects`.`is_public` AS t2_r4, 
       `projects`.`parent_id` AS t2_r5, 
       `projects`.`created_on` AS t2_r6, 
       `projects`.`updated_on` AS t2_r7, 
       `projects`.`identifier` AS t2_r8, 
       `projects`.`status` AS t2_r9, 
       `projects`.`lft` AS t2_r10, 
       `projects`.`rgt` AS t2_r11, 
       `projects`.`inherit_members` AS t2_r12, 
       `projects`.`default_version_id` AS t2_r13, 
       `projects`.`default_assigned_to_id` AS t2_r14, 
       `projects`.`new_ticket_message` AS t2_r15, 
       `projects`.`enable_new_ticket_message` AS t2_r16, 
       `projects`.`default_issue_query_id` AS t2_r17 
FROM `helpdesk_tickets` 
LEFT OUTER JOIN `issues` ON `issues`.`id` = `helpdesk_tickets`.`issue_id` 
LEFT OUTER JOIN `projects` ON `projects`.`id` = `issues`.`project_id` 
WHERE `projects`.`id` = 161;

-- Analysis:
-- - Returns 17,156 rows
-- - 61 columns per row (19 + 24 + 18)
-- - Total data points: ~1,046,516
-- - Forces full table scan with eager loading
-- - Query times out after 120 seconds

-- ============================================
-- FAST QUERY (Optimized)
-- Generated by: HelpdeskTicket.joins(:issue).where(:issues => { project_id: 161 }).count
-- Performance: <100ms
-- ============================================

SELECT COUNT(*) 
FROM `helpdesk_tickets` 
INNER JOIN `issues` ON `issues`.`id` = `helpdesk_tickets`.`issue_id` 
WHERE `issues`.`project_id` = 161;

-- Analysis:
-- - Returns 1 row with single integer
-- - Uses index issues_project_id on WHERE clause
-- - Uses index index_helpdesk_tickets_on_issue_id_and_contact_id on JOIN
-- - Query completes in milliseconds

-- ============================================
-- FAST QUERY (Customer Count)
-- Generated by: HelpdeskTicket.joins(:issue)...distinct.count(:contact_id)
-- Performance: <100ms
-- ============================================

SELECT COUNT(DISTINCT `helpdesk_tickets`.`contact_id`) 
FROM `helpdesk_tickets` 
INNER JOIN `issues` ON `issues`.`id` = `helpdesk_tickets`.`issue_id` 
WHERE `issues`.`project_id` = 161 
AND `helpdesk_tickets`.`contact_id` IS NOT NULL;

-- Analysis:
-- - Returns 1 row with distinct count
-- - Uses same indexes as ticket count
-- - WHERE NOT NULL filters out tickets without contacts
-- - Query completes in milliseconds

-- ============================================
-- EXPLAIN PLAN Comparison
-- ============================================

-- Slow Query EXPLAIN:
-- EXPLAIN SELECT ... FROM helpdesk_tickets LEFT OUTER JOIN issues ... LEFT OUTER JOIN projects ... WHERE projects.id = 161;
-- Expected: Full table scan, no index usage on WHERE, temporary table for result

-- Fast Query EXPLAIN:
-- EXPLAIN SELECT COUNT(*) FROM helpdesk_tickets INNER JOIN issues ... WHERE issues.project_id = 161;
-- Expected: Using index issues_project_id, ref lookup, no temporary table

-- ============================================
-- Available Indexes (Verified)
-- ============================================

-- Issues table:
--   issues_project_id: (project_id)

-- HelpdeskTickets table:
--   index_helpdesk_tickets_on_issue_id_and_contact_id: (issue_id, contact_id)

-- These indexes support the fast queries but are not utilized by the includes() + count() pattern
